set(PPLNN_VERSION_MAJOR 0)
set(PPLNN_VERSION_MINOR 7)
set(PPLNN_VERSION_PATCH 0)

list(APPEND PPLNN_COMPILE_DEFINITIONS
    PPLNN_VERSION_MAJOR=${PPLNN_VERSION_MAJOR}
    PPLNN_VERSION_MINOR=${PPLNN_VERSION_MINOR}
    PPLNN_VERSION_PATCH=${PPLNN_VERSION_PATCH})

hpcc_get_git_info(
    GIT_HASH_OUTPUT PPLNN_COMMIT_HASH
    GIT_TAG_OUTPUT PPLNN_COMMIT_TAG)

set(__PPLNN_COMMIT_ID_SRC__ ${CMAKE_CURRENT_BINARY_DIR}/generated/commit.cc)

configure_file(
    ${CMAKE_CURRENT_SOURCE_DIR}/src/ppl/nn/utils/commit.cc.in
    ${__PPLNN_COMMIT_ID_SRC__}
    @ONLY)

list(APPEND PPLNN_SOURCES ${__PPLNN_COMMIT_ID_SRC__})
unset(__PPLNN_COMMIT_ID_SRC__)
