name: PPL<x86> Build && Quick Test

on:
  #push:
  #  branches: [ master ]
  #  paths-ignore: ['.**',  'docs/**', 'samples/**', README.md]
  pull_request:
    branches: [ master ]
    paths-ignore: ['.**',  'docs/**', 'samples/**', README.md]
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: self-hosted

    steps:
      - name: Test
        run: |
          cd ../../ && ./test_py_print.sh
